CREATE TABLE IF NOT EXISTS "user"(
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100),
    "email" varchar(100),
    "firstName" varchar(100),
    "lastName" varchar(100)
)